"""Added new changes to models

Revision ID: 137933aed414
Revises: 6afaf445bf67
Create Date: 2025-10-16 10:34:09.423651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137933aed414'
down_revision = '6afaf445bf67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_file', sa.String(length=120), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('program', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('campus', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('interests', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('interests')
        batch_op.drop_column('campus')
        batch_op.drop_column('program')
        batch_op.drop_column('bio')
        batch_op.drop_column('name')

    op.drop_table('post')
    # ### end Alembic commands ###
