"""Added Description for  Event Organizer

Revision ID: ad2bf7dba6b7
Revises: 6fcd5052b92e
Create Date: 2025-10-05 14:47:08.788965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2bf7dba6b7'
down_revision = '6fcd5052b92e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_organizer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_organizer', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
