"""Added Image for Event

Revision ID: 48fd455c48ba
Revises: ad2bf7dba6b7
Create Date: 2025-10-05 15:12:56.473656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fd455c48ba'
down_revision = 'ad2bf7dba6b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banner_image', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('banner_image')

    # ### end Alembic commands ###
