"""Edited Review

Revision ID: dc7c813084cc
Revises: 6b23e1981194
Create Date: 2025-10-09 21:43:16.199326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7c813084cc'
down_revision = '6b23e1981194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_rating', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('organizer_rating', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('event_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('organizer_coment', sa.Text(), nullable=True))
        batch_op.drop_column('review_type')
        batch_op.drop_column('rating')
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('review_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('organizer_coment')
        batch_op.drop_column('event_comment')
        batch_op.drop_column('organizer_rating')
        batch_op.drop_column('event_rating')

    # ### end Alembic commands ###
