"""Edited Review

Revision ID: b03e0fc9a08b
Revises: dc7c813084cc
Create Date: 2025-10-09 21:46:07.779307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03e0fc9a08b'
down_revision = 'dc7c813084cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_comment', sa.Text(), nullable=True))
        batch_op.drop_column('organizer_coment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_coment', sa.TEXT(), nullable=True))
        batch_op.drop_column('organizer_comment')

    # ### end Alembic commands ###
