"""Edited Event.reasons_to_attend

Revision ID: b3c81279b2a6
Revises: 9c3f6d1db863
Create Date: 2025-10-05 15:38:27.856276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3c81279b2a6'
down_revision = '9c3f6d1db863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reasons_to_attend', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('reasons_to_attend')

    # ### end Alembic commands ###
